const STORE_NUMBER_REQUEST = 'STORE_NUMBER_REQUEST'
const STORE_NUMBER_SUCCESS = 'STORE_NUMBER_SUCCESS'
const STORE_NUMBER_ERROR = 'STORE_NUMBER_ERROR'

export {STORE_NUMBER_SUCCESS,STORE_NUMBER_ERROR,STORE_NUMBER_REQUEST}